travis:
  secure:
    BINSTAR_TOKEN: dR3YjCEIk7Sp76sbvLnLpK+fiMR3A3GgoeFqqr9f6S/zJdAdAb2HC0lZTVjSXVQW78Yot9I/LamqXZIG/CfHNRj0HXtRSWxciWDP5TBAgw3CWhVxIt3eHYsL9RWIiLAxRcdMfArB0lKPqI6oxHur52zOdO+K/pMbJsYw7zr14Vg6m3/slrUVCZW0zTwQ72h8m4d1vn89269dthPyKVuGuLPNNrLu4xfstJx2T1BafvpJPAKTg/xYkVN8WORyO3jOvWokl0/kZXb8Cf437lN0Kxk2ESyhb52qTyB94ABzl4GBcnKKWuC2iz3D3UuLY0ln9ZdpR8sqePpAywPkH54njNtZvQFD5DQ/VSY/d5wSPUIV8ygQMc+IfqIA4hW99e0IgLfOpfVhiBwAe0gbJmvrB+orKHHZd5UfBb6BMHfATCs2/qitiDbuLbQhlk7h1CO5waCQAmAsLWQ4J8kuxEZnSC1vmfMyZyMk4Lu/TVn+U8Ms3eCzpxZ2fkWj4g8crXsSolxXEdhmvKpv8YjeGpQ1INKXQ/V+qdeKacPifadARejgB7OGkF/JR+/xJp7NLi97DtvI3vQ3ISjLajdZZxLyvz/JPTpWttcDXa2oVuXbsB9XrYrmuublpCtXf/ybF9qrIsOZLc+ypjWVrP+eAK47WO7FSlAgtHRzoQ9WAgOF45k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
